<!DOCTYPE html>
<html>
    <head>
        <title>Membership Report</title>
        <link rel="stylesheet" type="text/css" href="/css/main.css"/>
    </head>
    <body>
        <div class="content flex-container">
            <ul class="side-nav">
                <a href="#"><h1>View Reports</h1></a>
                <a class="active link" href="/reports/membership">Membership</a>
                <a class="link" href="/reports/staff">Staff</a>
                <a class="link" href="/logout">Logout</a>
            </ul>
            <div class="graphs">
                <h1>Membership Report</h1>
            </div>
        </div>
    </body>
</html>